version: '3'
services:
  python3_modules:
    working_dir: '/code/'
    tty: true
    build: ./python
    volumes:
      - .:/code
    depends_on:
      - dynamodb
    env_file:
      - ./.env/env_file
  dynamodb:
    build: ./dynamodb
    container_name: dynamodb
    volumes:
      - ./dynamodb/data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath ./data